customhost = "employee1.cscpwxzgprej.us-east-2.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "Ranjith2000"
customdb = "employee"
custombucket = "addemployeesql"
customregion = "us-east-2"
